"Ne mora te teneat,"
"Ne cunctare precor,"
"Diva Thalia jubet,"
"Docta Thalia jubet,"
"Eja agedum! Lubeat,"
"Quod peto, sponte voles,"
"Quod precor, ipse voles,"
"Ne dedigneris,"
"Sit tibi chare placens,"
"Non detrectabis,"
"Promptus, Amice, velis,"
"Te mora nulla liget,"
"Haud erit ingratum,"
"Ne grave fit, quæso,"
"Dignare, obtestor,"
"Haud, credo renues,"
"Non tibi displiceat,"
"Ne tibi displiceat,"
"Præses Apollo jubet,"
"Pieris alma jubet,"
"Te mandat Phoebus,"
"Sponte tua cupies,"
"Spero, non renues,"
"chartæ perfringere gemmam,"
"fua vincula demere chartæ,"
"tectis admittere chartam,"
"præsentem evolvere chartam,"
"peregrinam evolvere chartam,"
"concedere lumina chartæ,"
"percurrere lumine chartam,"
"nostram acceptare tabellam,"
"chartæ perfringere ceram,"
"chartam lustrare legendo,"
"lustare hanc lumine chartam,"
"lustare legendo tabellam,"
"fua vincula tollere chartæ,"
"vúltum concedere chartæ,"
"valtum indulgere tabellæ,"
"fua vincula solvere chartae,"
"quam cernis volvere chartam,"
"fua vincula rumpere chartae,"
"peregrinam volvere chartam,"
"nostræ dare lumina chartæ,"
"fua tollere vincula tabellæ,"
"concedere limina chartæ,"
"præsentem volvere chartam,"
"Non ex ignotis,"
"Non ex ingratis,"
"Non ex Odrysiis,"
"Non ex barbaricis,"
"Non ex Sarmaticis,"
"E tibi jucundis,"
"Ex tibi jucundis,"
"E tibi dilectis,"
"Ex tibi dilectis,"
":[ E tibi ter charts,"
"Ex tibi pergratis;"
"Ex tibi fat notis,"
"Non ex infaustis,"
"Non ex invisis,"
"Non ex Iliacis,"
"Non ex fædifragis,"
"a tibi dilectis,"
"a tibi pergratis,"
"à tibi fat notis,"
"E fortunatis,"
"Neutiquam ab ignotis,"
"Ex non ignotis,"
"Ex non ingratis,"
"Scribitur illa plagis"
"mittitur illa plagis"
"advenit illa plagis"
"devenit illa plagis"
"prodiit illa plagis"
"hanc tibi mitto plagis"
"& ea misa plagis"
"& ea scripta plagis"
"crede, venire plagis"
"dat tibi penna plagis,"
"tractibus illa venit"
"partibus illa venit"
"sedibus illa venit"
"sinibus illa venit"
"scribitur illa locis"
"mittitur illa locis"
"advenit illa locis"

#split 1

"devenit illa locis"
"prodiit illa locis"
"hanc tibi mitto locis"
"est ea missa locis"
"est ea scripta locis"
"hanc tibi scribo Locis"
"Non tibi satales"
"Non tibi funereos"
"Non tibi bellicrepos"
"Non infelices"
"Non importunos"
"Non conclamatos"
"Non ærumnosos"
"Non portentosos"
"Non tibi terrificos"
"Non tibi satidicos"
"Non injucundos"
"Non tibi mortiferos"
"Non tibi funestos"
"Non tibi damniseros"
"Non tibi damnosos"
"Non tibi ferales"
"Non tibi præproperos"
"Non tibi luctisonos"
"Non tibi terribiles"
"Non tibi secretos"
"Non plorabundos"
"Non infestivos"
"Non inpermissos"
"depinget epistola questus"
"depinget epistola casus"
"evolvet epistola questus"
"evolver epistola casus"
"describet epistola questus"
"describet epistola casus"
"narrabit epistola questus"
"narrabit epistola casus"
"memorabit epistola questus"
"memorabit epistola casus"
"exponet epistola casus"
"exponet epistola questus"
"effundet epistola questus"
"effundet epistola casus"
"mea narrat epistola questus"
"mea narrat epistola casus"
"mea pandet epistola questus"
"mea pandet epistola casus"
"referet mea littera questus"
"referet mea littera casus"
"pandet mea littera questus"
"depinget littera casus"
"describet littera questus"
"Mentis delicias"
"causas lætitiæ"
"lætitiæ causas"
"luctu delicias"
"Cordis lætitias"
"Delicias animi"
"Delicias luctu"
"lætitias animi"
"lætitias mentis"
"Cordis delicias"
"sanas delicias"
"sanctas delicias"
"Delicias animæ"
"Cellæ delicias"
"Delicias lachrymis"
"lætitias luctu"
"Pacis delicias"
"Sanctas illecebras"
"Præfica lætitias"
"tristis delicias"
"castas illecebras"
"Tristibus illecebras"
"Delicias pacis"
"curat & illa tuas"
"servat & illa tuas"
"tollat ut illa tuas"
"non vetat illa tuas"
"solvat ut illa tuas"
"sternat ut illa tuas"
"non necat illa tuas"
"diligit illa tuas"
"demat ut illa tuas"
"perdat ut illa tuas"
"non ego tollo tuas"
"non ego turbo tuas"
"non ego pello tuas"
"pellat ut illa tuas"
"non rapit illa tuas"
"deperit ipsa tuas"
"nam fovet ipsa tuas"

#split 2

"frangat ut illa tuas"
"rumpat ut illa tuas"
"pulset ut illa tuas"
"dejiciendo tuas"
"non ego demo, tuas"
"fors remorando tuas"
"Arx est nota tibi"
"grata tibi domus est"
"sat tibi nota domus"
"est tibi nota domus"
"est tibi grata domus"
"est tibi chara domus"
"Nota tibi domus est"
"est bene nota domus"
"chara tibi domus est"
"nota est aula tibi"
"aula tibi nota est"
"ædes chara tibi est"
"ædes nota tibi est"
"cognita sat domus est"
"est mea nota domus"
"est sat nota domus"
"Patria nota tibi est"
"Nota tibi patria est"
"nostra domus nota est"
"Cognita nostra domus"
"est dilecta domus"
"est peramata domus"
"Non domus exosa est"
"nec nomina nostra requires"
"quæ talia vidit arantem"
"quæ carmina vidit arantem"
"notus tibi carminis author"
"qua Vates Incola vivit"
"qua Vates prodiit olim"
"quæ nostro carmine gaudet"
"quæ te veneratur, & audit"
"notus, quem diligis, author"
"quæ pro te metra paravit"
"notus, qui scribit, amicus"
"qui scripsit, notus amicus"
"charus, qui carmine ludit,"
"gratus, qui metra paravit"
"multo fum cognitus ufu,"
"multos tibi culta per annos"
"chari, gratique fodalis,"
"qua degit carminis author"
"qua præsens littera prodit"
"qua dulcis epistola venit"
"chari, gratique penates"
"scribentis stemma, manusque"
"scriptoris dextra, genusque"
"Tu mihi pars cordis"
"tu mihi præsidium"
"semper eras Tutor"
"semper eras Ductor,"
"semper eras Pylades"
"Tu mihi cordis amor"
"tu mihi cor cordis"
"Tu mihi dulcis amor"
"semper Nisus eras"
"Tu mihi Patronus"
"Tu mihi Mecenas"
"Tu mihi Protector"
"Tu tutela mihi"
"Tu grandis Fautor"
"Tu Benefactor eras"
"Auxilio fueras"
"Præsidium fueras"
"Patronus mihi tu"
"Tu mihi solamen"
"Mecænas fueras"
"Ductor semper eras"
"Te colo fautorem,"
"Te colo Patronum"
"Deliciæque mex"
"Gloria quanta mihi!"
"Numinis ecce favor"
"Dux meus, alter ego"
"Theseus, alter ego"
"Duxque, salusque meis"
"Duxque, salusque mihi"
"Spes mea, dulce decus"
"Lux mea, dulce decus"
"Lux mea, dextra mihi"
"gratia summa mihi"
"perge manere, precor"

#split 3

"quod mihi nemo neget"
"quis neget ista mihi?"
"magne repende Deus!"
"quod benefacta notant"
"debeo cuncta tibi"
"quod mea Musa canit"
"quod mea Musa canet"
"tempus in omne mane"
"non ego dignus eram"
"talis & usque mane"
"perge favere precor"
"Justitiam sequeris"
"Virtutem sequeris"
"sectaris Themidem"
"Tu recti custos"
"Justitiam observas"
"Tu candoris amans"
"Justitiam servas"
"Non nisi justa facis"
"Cuique suum tribuis"
"Jura tueris amans"
"Grandia facta geris"
"Consilio gravis es"
"Majestate vales"
"Consilio polles"
"Polles consilio"
"Eloquio prestas"
"Judicio polles"
"Judicio prestas"
"Polles ingenio"
"Ingenio prestas"
"Laudari refugis"
"Non tibi laudis amor"
"laudari renuis."
"magna probitate coruscas"
"multa pietate coruscas"
"famæ mendacia rides"
"legum nec amantior alter"
"pietatis idoneus author"
"nulli pietate secundus"
"pietatem pectore spiras"
"solidæ pietatis alumnus"
"tibi Christi nomen amori"
"pietas tibi plurima cordi"
"pietas te laudibus ornat"
"sanctæ pietatis imago es"
"probitatis laude coruscas"
"pietas te nutrit alumnum"
"servas mandata Tonantis"
"totusque â Numine pendes"
"tibi mens sapit integra colum"
"pietas tibi maxima rerum"
"pietas tibi pectore fixa est"
"vera pietate coruscas"
"concludis pectore cœlum"
"probitas te gaudet alumno"
"pietas te gaudet Achate"
"Haud te noxa premit"
"Indolis es placidæ"
"Non vitiis traheris"
"Criminis innocuus"
"Numine digna sapis"
"Exemplar morum es"
"Grande decus patriæ es"
"Integer es vitæ"
"Es purus sceleris"
"Expers tu sceleris"
"Cedro digna geris"
"Marmore digna geris"
"Cunctis diligeris"
"Te genus exornat"
"Diligeris cunctis"
"Devincis cunctos"
"Magnus in adversis"
"Castior Hippolito es"
"Quantum animo prestas!"
"Fortior adversis"
"Quis te digna canet?"
"Vis generosa tibi"
"Excellis cunctos"
"Spes tua sola Deus"
"Candida corda geris"
"Lactea corda geris"
"Corda pudica geris"
"Cor patientis habes"
"Non tibi nota Venus"
"Quot tibi mentis opes!"
"pectore fucus abest"
"sidera mente geris"

#split 4

"fors bona semper amet!"
"semper ad alta volas"
"celsius ire nequis"
"nomen ad astra vehis"
"mens tibi casta placet"
"mens tibi pura placer"
"fama perennis erit"
"non tibi parca manus"
"quam tibi larga manus"
"non tibi fastus inest"
"te Cytherea fugit"
"spes tua tota Deus"
"mens animosa tibi"
"Dona quot alma tibi!"
