# The table is an array of dictionaries of arrays

table = [{'a':['Ne mora te teneat,',"Don't let delay hold you back"],
'b':['Ne cunctare precor,',"I pray you not to delay"],
'c':['Diva Thalia jubet,',"test"],
'd':['Docta Thalia jubet,',"test"],
'e':['Eja agedum! Lubeat,',"test"],
'f':['Quod peto, sponte voles,',"test"],
'g':['Quod precor, ipse voles,',"test"],
'h':['Ne dedigneris,',"test"],
'i':['Sit tibi chare placens,',"test"],
'k':['Non detrectabis,',"test"],
'l':['Promptus, Amice, velis,',"test"],
'm':['Te mora nulla liget,',"test"],
'n':['Haud erit ingratum,',"test"],
'o':['Ne grave fit, quæso,',"test"],
'p':['Dignare, obtestor,',"test"],
'q':['Haud, credo renues,',"test"],
'r':['Non tibi displiceat,',"test"],
's':['Ne tibi displiceat,',"test"],
't':['Præses Apollo jubet,',"test"],
'v':['Pieris alma jubet,',"test"],
'w':['Te mandat Phoebus,',"test"],
'x':['Sponte tua cupies,',"test"],
'z':['Spero, non renues,',"test"],
},
{'a':['chartæ perfringere gemmam,',"test"],
'b':['fua vincula demere chartæ,',"test"],
'c':['tectis admittere chartam,',"test"],
'd':['præsentem evolvere chartam,',"test"],
'e':['peregrinam evolvere chartam,',"test"],
'f':['concedere lumina chartæ,',"test"],
'g':['percurrere lumine chartam,',"test"],
'h':['nostram acceptare tabellam,',"test"],
'i':['chartæ perfringere ceram,',"test"],
'k':['chartam lustrare legendo,',"test"],
'l':['lustare hanc lumine chartam,',"test"],
'm':['lustare legendo tabellam,',"test"],
'n':['fua vincula tollere chartæ,',"test"],
'o':['vúltum concedere chartæ,',"test"],
'p':['valtum indulgere tabellæ,',"test"],
'q':['fua vincula solvere chartae,',"test"],
'r':['quam cernis volvere chartam,',"test"],
's':['fua vincula rumpere chartae,',"test"],
't':['peregrinam volvere chartam,',"test"],
'v':['nostræ dare lumina chartæ,',"test"],
'w':['fua tollere vincula tabellæ,',"test"],
'x':['concedere limina chartæ,',"test"],
'z':['præsentem volvere chartam,',"test"],
},
{'a':['Non ex ignotis,',"test"],
'b':['Non ex ingratis,',"test"],
'c':['Non ex Odrysiis,',"test"],
'd':['Non ex barbaricis,',"test"],
'e':['Non ex Sarmaticis,',"test"],
'f':['E tibi jucundis,',"test"],
'g':['Ex tibi jucundis,',"test"],
'h':['E tibi dilectis,',"test"],
'i':['Ex tibi dilectis,',"test"],
'k':[':[ E tibi ter charts,',"test"],
'l':['Ex tibi pergratis;',"test"],
'm':['Ex tibi fat notis,',"test"],
'n':['Non ex infaustis,',"test"],
'o':['Non ex invisis,',"test"],
'p':['Non ex Iliacis,',"test"],
'q':['Non ex fædifragis,',"test"],
'r':['a tibi dilectis,',"test"],
's':['a tibi pergratis,',"test"],
't':['à tibi fat notis,',"test"],
'v':['E fortunatis,',"test"],
'w':['Neutiquam ab ignotis,',"test"],
'x':['Ex non ignotis,',"test"],
'z':['Ex non ingratis,',"test"],
},
{'a':['Scribitur illa plagis',"test"],
'b':['mittitur illa plagis',"test"],
'c':['advenit illa plagis',"test"],
'd':['devenit illa plagis',"test"],
'e':['prodiit illa plagis',"test"],
'f':['hanc tibi mitto plagis',"test"],
'g':['& ea misa plagis',"test"],
'h':['& ea scripta plagis',"test"],
'i':['crede, venire plagis',"test"],
'k':['dat tibi penna plagis,',"test"],
'l':['tractibus illa venit',"test"],
'm':['partibus illa venit',"test"],
'n':['sedibus illa venit',"test"],
'o':['sinibus illa venit',"test"],
'p':['scribitur illa locis',"test"],
'q':['mittitur illa locis',"test"],
'r':['advenit illa locis',"test"],
's':['devenit illa locis',"test"],
't':['prodiit illa locis',"test"],
'v':['hanc tibi mitto locis',"test"],
'w':['est ea missa locis',"test"],
'x':['est ea scripta locis',"test"],
'z':['hanc tibi scribo Locis',"test"],
},
{'a':['Non tibi satales',"test"],
'b':['Non tibi funereos',"test"],
'c':['Non tibi bellicrepos',"test"],
'd':['Non infelices',"test"],
'e':['Non importunos',"test"],
'f':['Non conclamatos',"test"],
'g':['Non ærumnosos',"test"],
'h':['Non portentosos',"test"],
'i':['Non tibi terrificos',"test"],
'k':['Non tibi satidicos',"test"],
'l':['Non injucundos',"test"],
'm':['Non tibi mortiferos',"test"],
'n':['Non tibi funestos',"test"],
'o':['Non tibi damniseros',"test"],
'p':['Non tibi damnosos',"test"],
'q':['Non tibi ferales',"test"],
'r':['Non tibi præproperos',"test"],
's':['Non tibi luctisonos',"test"],
't':['Non tibi terribiles',"test"],
'v':['Non tibi secretos',"test"],
'w':['Non plorabundos',"test"],
'x':['Non infestivos',"test"],
'z':['Non inpermissos',"test"],
},
{'a':['depinget epistola questus',"test"],
'b':['depinget epistola casus',"test"],
'c':['evolvet epistola questus',"test"],
'd':['evolver epistola casus',"test"],
'e':['describet epistola questus',"test"],
'f':['describet epistola casus',"test"],
'g':['narrabit epistola questus',"test"],
'h':['narrabit epistola casus',"test"],
'i':['memorabit epistola questus',"test"],
'k':['memorabit epistola casus',"test"],
'l':['exponet epistola casus',"test"],
'm':['exponet epistola questus',"test"],
'n':['effundet epistola questus',"test"],
'o':['effundet epistola casus',"test"],
'p':['mea narrat epistola questus',"test"],
'q':['mea narrat epistola casus',"test"],
'r':['mea pandet epistola questus',"test"],
's':['mea pandet epistola casus',"test"],
't':['referet mea littera questus',"test"],
'v':['referet mea littera casus',"test"],
'w':['pandet mea littera questus',"test"],
'x':['depinget littera casus',"test"],
'z':['describet littera questus',"test"],
},
{'a':['Mentis delicias',"test"],
'b':['causas lætitiæ',"test"],
'c':['lætitiæ causas',"test"],
'd':['luctu delicias',"test"],
'e':['Cordis lætitias',"test"],
'f':['Delicias animi',"test"],
'g':['Delicias luctu',"test"],
'h':['lætitias animi',"test"],
'i':['lætitias mentis',"test"],
'k':['Cordis delicias',"test"],
'l':['sanas delicias',"test"],
'm':['sanctas delicias',"test"],
'n':['Delicias animæ',"test"],
'o':['Cellæ delicias',"test"],
'p':['Delicias lachrymis',"test"],
'q':['lætitias luctu',"test"],
'r':['Pacis delicias',"test"],
's':['Sanctas illecebras',"test"],
't':['Præfica lætitias',"test"],
'v':['tristis delicias',"test"],
'w':['castas illecebras',"test"],
'x':['Tristibus illecebras',"test"],
'z':['Delicias pacis',"test"],
},
{'a':['curat & illa tuas',"test"],
'b':['servat & illa tuas',"test"],
'c':['tollat ut illa tuas',"test"],
'd':['non vetat illa tuas',"test"],
'e':['solvat ut illa tuas',"test"],
'f':['sternat ut illa tuas',"test"],
'g':['non necat illa tuas',"test"],
'h':['diligit illa tuas',"test"],
'i':['demat ut illa tuas',"test"],
'k':['perdat ut illa tuas',"test"],
'l':['non ego tollo tuas',"test"],
'm':['non ego turbo tuas',"test"],
'n':['non ego pello tuas',"test"],
'o':['pellat ut illa tuas',"test"],
'p':['non rapit illa tuas',"test"],
'q':['deperit ipsa tuas',"test"],
'r':['nam fovet ipsa tuas',"test"],
's':['frangat ut illa tuas',"test"],
't':['rumpat ut illa tuas',"test"],
'v':['pulset ut illa tuas',"test"],
'w':['dejiciendo tuas',"test"],
'x':['non ego demo, tuas',"test"],
'z':['fors remorando tuas',"test"],
},
{'a':['Arx est nota tibi',"test"],
'b':['grata tibi domus est',"test"],
'c':['sat tibi nota domus',"test"],
'd':['est tibi nota domus',"test"],
'e':['est tibi grata domus',"test"],
'f':['est tibi chara domus',"test"],
'g':['Nota tibi domus est',"test"],
'h':['est bene nota domus',"test"],
'i':['chara tibi domus est',"test"],
'k':['nota est aula tibi',"test"],
'l':['aula tibi nota est',"test"],
'm':['ædes chara tibi est',"test"],
'n':['ædes nota tibi est',"test"],
'o':['cognita sat domus est',"test"],
'p':['est mea nota domus',"test"],
'q':['est sat nota domus',"test"],
'r':['Patria nota tibi est',"test"],
's':['Nota tibi patria est',"test"],
't':['nostra domus nota est',"test"],
'v':['Cognita nostra domus',"test"],
'w':['est dilecta domus',"test"],
'x':['est peramata domus',"test"],
'z':['Non domus exosa est',"test"],
},
{'a':['nec nomina nostra requires',"test"],
'b':['quæ talia vidit arantem',"test"],
'c':['quæ carmina vidit arantem',"test"],
'd':['notus tibi carminis author',"test"],
'e':['qua Vates Incola vivit',"test"],
'f':['qua Vates prodiit olim',"test"],
'g':['quæ nostro carmine gaudet',"test"],
'h':['quæ te veneratur, & audit',"test"],
'i':['notus, quem diligis, author',"test"],
'k':['quæ pro te metra paravit',"test"],
'l':['notus, qui scribit, amicus',"test"],
'm':['qui scripsit, notus amicus',"test"],
'n':['charus, qui carmine ludit,',"test"],
'o':['gratus, qui metra paravit',"test"],
'p':['multo fum cognitus ufu,',"test"],
'q':['multos tibi culta per annos',"test"],
'r':['chari, gratique fodalis,',"test"],
's':['qua degit carminis author',"test"],
't':['qua præsens littera prodit',"test"],
'v':['qua dulcis epistola venit',"test"],
'w':['chari, gratique penates',"test"],
'x':['scribentis stemma, manusque',"test"],
'z':['scriptoris dextra, genusque',"test"],
},
{'a':['Tu mihi pars cordis',"test"],
'b':['tu mihi præsidium',"test"],
'c':['semper eras Tutor',"test"],
'd':['semper eras Ductor,',"test"],
'e':['semper eras Pylades',"test"],
'f':['Tu mihi cordis amor',"test"],
'g':['tu mihi cor cordis',"test"],
'h':['Tu mihi dulcis amor',"test"],
'i':['semper Nisus eras',"test"],
'k':['Tu mihi Patronus',"test"],
'l':['Tu mihi Mecenas',"test"],
'm':['Tu mihi Protector',"test"],
'n':['Tu tutela mihi',"test"],
'o':['Tu grandis Fautor',"test"],
'p':['Tu Benefactor eras',"test"],
'q':['Auxilio fueras',"test"],
'r':['Præsidium fueras',"test"],
's':['Patronus mihi tu',"test"],
't':['Tu mihi solamen',"test"],
'v':['Mecænas fueras',"test"],
'w':['Ductor semper eras',"test"],
'x':['Te colo fautorem,',"test"],
'z':['Te colo Patronum',"test"],
},
{'a':['Deliciæque mex',"test"],
'b':['Gloria quanta mihi!',"test"],
'c':['Numinis ecce favor',"test"],
'd':['Dux meus, alter ego',"test"],
'e':['Theseus, alter ego',"test"],
'f':['Duxque, salusque meis',"test"],
'g':['Duxque, salusque mihi',"test"],
'h':['Spes mea, dulce decus',"test"],
'i':['Lux mea, dulce decus',"test"],
'k':['Lux mea, dextra mihi',"test"],
'l':['gratia summa mihi',"test"],
'm':['perge manere, precor',"test"],
'n':['quod mihi nemo neget',"test"],
'o':['quis neget ista mihi?',"test"],
'p':['magne repende Deus!',"test"],
'q':['quod benefacta notant',"test"],
'r':['debeo cuncta tibi',"test"],
's':['quod mea Musa canit',"test"],
't':['quod mea Musa canet',"test"],
'v':['tempus in omne mane',"test"],
'w':['non ego dignus eram',"test"],
'x':['talis & usque mane',"test"],
'z':['perge favere precor',"test"],
},
{'a':['Justitiam sequeris',"test"],
'b':['Virtutem sequeris',"test"],
'c':['sectaris Themidem',"test"],
'd':['Tu recti custos',"test"],
'e':['Justitiam observas',"test"],
'f':['Tu candoris amans',"test"],
'g':['Justitiam servas',"test"],
'h':['Non nisi justa facis',"test"],
'i':['Cuique suum tribuis',"test"],
'k':['Jura tueris amans',"test"],
'l':['Grandia facta geris',"test"],
'm':['Consilio gravis es',"test"],
'n':['Majestate vales',"test"],
'o':['Consilio polles',"test"],
'p':['Polles consilio',"test"],
'q':['Eloquio prestas',"test"],
'r':['Judicio polles',"test"],
's':['Judicio prestas',"test"],
't':['Polles ingenio',"test"],
'v':['Ingenio prestas',"test"],
'w':['Laudari refugis',"test"],
'x':['Non tibi laudis amor',"test"],
'z':['laudari renuis.',"test"],
},
{'a':['magna probitate coruscas',"test"],
'b':['multa pietate coruscas',"test"],
'c':['famæ mendacia rides',"test"],
'd':['legum nec amantior alter',"test"],
'e':['pietatis idoneus author',"test"],
'f':['nulli pietate secundus',"test"],
'g':['pietatem pectore spiras',"test"],
'h':['solidæ pietatis alumnus',"test"],
'i':['tibi Christi nomen amori',"test"],
'k':['pietas tibi plurima cordi',"test"],
'l':['pietas te laudibus ornat',"test"],
'm':['sanctæ pietatis imago es',"test"],
'n':['probitatis laude coruscas',"test"],
'o':['pietas te nutrit alumnum',"test"],
'p':['servas mandata Tonantis',"test"],
'q':['totusque â Numine pendes',"test"],
'r':['tibi mens sapit integra colum',"test"],
's':['pietas tibi maxima rerum',"test"],
't':['pietas tibi pectore fixa est',"test"],
'v':['vera pietate coruscas',"test"],
'w':['concludis pectore cœlum',"test"],
'x':['probitas te gaudet alumno',"test"],
'z':['pietas te gaudet Achate',"test"],
},
{'a':['Haud te noxa premit',"test"],
'b':['Indolis es placidæ',"test"],
'c':['Non vitiis traheris',"test"],
'd':['Criminis innocuus',"test"],
'e':['Numine digna sapis',"test"],
'f':['Exemplar morum es',"test"],
'g':['Grande decus patriæ es',"test"],
'h':['Integer es vitæ',"test"],
'i':['Es purus sceleris',"test"],
'k':['Expers tu sceleris',"test"],
'l':['Cedro digna geris',"test"],
'm':['Marmore digna geris',"test"],
'n':['Cunctis diligeris',"test"],
'o':['Te genus exornat',"test"],
'p':['Diligeris cunctis',"test"],
'q':['Devincis cunctos',"test"],
'r':['Magnus in adversis',"test"],
's':['Castior Hippolito es',"test"],
't':['Quantum animo prestas!',"test"],
'v':['Fortior adversis',"test"],
'w':['Quis te digna canet?',"test"],
'x':['Vis generosa tibi',"test"],
'z':['Excellis cunctos',"test"],
},
{'a':['Spes tua sola Deus',"test"],
'b':['Candida corda geris',"test"],
'c':['Lactea corda geris',"test"],
'd':['Corda pudica geris',"test"],
'e':['Cor patientis habes',"test"],
'f':['Non tibi nota Venus',"test"],
'g':['Quot tibi mentis opes!',"test"],
'h':['pectore fucus abest',"test"],
'i':['sidera mente geris',"test"],
'k':['fors bona semper amet!',"test"],
'l':['semper ad alta volas',"test"],
'm':['celsius ire nequis',"test"],
'n':['nomen ad astra vehis',"test"],
'o':['mens tibi casta placet',"test"],
'p':['mens tibi pura placer',"test"],
'q':['fama perennis erit',"test"],
'r':['non tibi parca manus',"test"],
's':['quam tibi larga manus',"test"],
't':['non tibi fastus inest',"test"],
'v':['te Cytherea fugit',"test"],
'w':['spes tua tota Deus',"test"],
'x':['mens animosa tibi',"test"],
'z':['Dona quot alma tibi!',"test"],
}],