# The table is an array of dictionaries of arrays

table = [{"a":['Ne mora te teneat,', 'Do not let delay hold you,'],
"b":['Ne cunctare precor,', 'Do not hesitate, I beg,'],
"c":['Diva Thalia jubet,', 'Divine Thalia commands,'],
"d":['Docta Thalia jubet,', 'Learned Thalia commands,'],
"e":['Eja agedum! Lubeat,', 'Come on now! Be pleased,'],
"f":['Quod peto, sponte voles,', 'What I ask, you will willingly want,'],
"g":['Quod precor, ipse voles,', 'What I beg, you will want yourself,'],
"h":['Ne dedigneris,', 'Do not disdain,'],
"i":['Sit tibi chare placens,', 'May it be pleasing and dear to you,'],
"k":['Non detrectabis,', 'You will not reject,'],
"l":['Promptus, Amice, velis,', 'Ready, Friend, as you wish,'],
"m":['Te mora nulla liget,', 'Let no delay hold you,'],
"n":['Haud erit ingratum,', 'It will not be ungrateful,'],
"o":['Ne grave fit, quæso,', 'Please do not let it become heavy,'],
"p":['Dignare, obtestor,', 'Deign, I beg,'],
"q":['Haud, credo renues,', 'I do not believe you will refuse,'],
"r":['Non tibi displiceat,', 'May it not displease you,'],
"s":['Ne tibi displiceat,', 'May it not displease you,'],
"t":['Præses Apollo jubet,', 'President Apollo commands,'],
"v":['Pieris alma jubet,', 'The beloved Pieris commands,'],
"w":['Te mandat Phoebus,', 'Phoebus entrusts you,'],
"x":['Sponte tua cupies,', 'You will willingly desire,'],
"z":['Spero, non renues,', 'I hope you will not refuse,'],
},
{"a":['chartæ perfringere gemmam,', 'Not from the unknown,'],
"b":['fua vincula demere chartæ,', 'to remove the bonds of the paper,'],
"c":['tectis admittere chartam,', 'to admit paper to the roof,'],
"d":['præsentem evolvere chartam,', 'to unfold the present paper,'],
"e":['peregrinam evolvere chartam,', 'to unfold the foreign paper,'],
"f":['concedere lumina chartæ,', 'to give light to the paper,'],
"g":['percurrere lumine chartam,', 'to run through the paper with light,'],
"h":['nostram acceptare tabellam,', 'to accept our tablet,'],
"i":['chartæ perfringere ceram,', 'to break the wax of the paper,'],
"k":['chartam lustrare legendo,', 'to polish the paper by reading,'],
"l":['lustare hanc lumine chartam,', 'to polish this paper with light,'],
"m":['lustare legendo tabellam,', 'to polish the tablet by reading,'],
"n":['fua vincula tollere chartæ,', 'to remove the bonds of the paper,'],
"o":['vúltum concedere chartæ,', 'to give a face to the paper,'],
"p":['valtum indulgere tabellæ,', 'to give a face to the tablet,'],
"q":['fua vincula solvere chartae,', 'to remove the bonds of the paper,'],
"r":['quam cernis volvere chartam,', 'to roll the paper you see,'],
"s":['fua vincula rumpere chartae,', 'to break the bonds of the paper,'],
"t":['peregrinam volvere chartam,', 'to roll the foreign paper,'],
"v":['nostræ dare lumina chartæ,', 'to give light to our paper,'],
"w":['fua tollere vincula tabellæ,', 'to remove the bonds of the tablet,'],
"x":['concedere limina chartæ,', 'to give light to the paper,'],
"z":['præsentem volvere chartam,', 'to unfold the present paper,'],
},
{"a":['Non ex ignotis,', 'It is written by the places,'],
"b":['Non ex ingratis,', 'Not from the ungrateful,'],
"c":['Non ex Odrysiis,', 'Not from the Odrysiis,'],
"d":['Non ex barbaricis,', 'Not from the barbarians,'],
"e":['Non ex Sarmaticis,', 'Not from the Sarmatians,'],
"f":['E tibi jucundis,', 'From the pleasing to you,'],
"g":['Ex tibi jucundis,', 'From the pleasing to you,'],
"h":['E tibi dilectis,', 'From the beloved to you,'],
"i":['Ex tibi dilectis,', 'From the beloved to you,'],
"k":['E tibi ter charts,', 'From the pleasing to you, the charts,'],
"l":['Ex tibi pergratis;', 'From the pleasing to you, the foreigners,'],
"m":['Ex tibi fat notis,', 'From the pleasing to you, the known,'],
"n":['Non ex infaustis,', 'Not from the unfortunate,'],
"o":['Non ex invisis,', 'Not from the unwanted,'],
"p":['Non ex Iliacis,', 'Not from the Iliac,'],
"q":['Non ex fædifragis,', 'Not from the shameful,'],
"r":['a tibi dilectis,', 'From the beloved to you,'],
"s":['a tibi pergratis,', 'From the pleasing to you,'],
"t":['à tibi fat notis,', 'From the pleasing to you, the known,'],
"v":['E fortunatis,', 'From the fortunate,'],
"w":['Neutiquam ab ignotis,', 'By no means from the unknown,'],
"x":['Ex non ignotis,', 'Not from the unknown,'],
"z":['Ex non ingratis,', 'Not from the ungrateful,'],
},
{"a":['Scribitur illa plagis', 'Not from the banquets,'],
"b":['mittitur illa plagis', 'It is sent by the places,'],
"c":['advenit illa plagis', 'It arrives by the places,'],
"d":['devenit illa plagis', 'It arrives by the places,'],
"e":['prodiit illa plagis', 'It comes out by the places,'],
"f":['hanc tibi mitto plagis', 'I send this to you by the places,'],
"g":['& ea misa plagis', '& it is sent by the places,'],
"h":['& ea scripta plagis', '& it is written by the places,'],
"i":['crede, venire plagis', 'Believe it will come by the places,'],
"k":['dat tibi penna plagis,', 'It gives you by the pen by the places,'],
"l":['tractibus illa venit', 'It comes by the tracts'],
"m":['partibus illa venit', 'It comes by the parts'],
"n":['sedibus illa venit', 'It comes by the seats'],
"o":['sinibus illa venit', 'It comes by the folds'],
"p":['scribitur illa locis', 'It is written by the places'],
"q":['mittitur illa locis', 'It is sent by the places'],
"r":['advenit illa locis', 'It arrives by the places'],
"s":['devenit illa locis', 'It arrives by the places,'],
"t":['prodiit illa locis', 'It comes out by the places,'],
"v":['hanc tibi mitto locis', 'I send this to you by the places,'],
"w":['est ea missa locis', 'It is sent by the places,'],
"x":['est ea scripta locis', 'It is written by the places,'],
"z":['hanc tibi scribo Locis', 'I write this to you by the places,'],
},
{"a":['Non tibi satales', 'The letter will depict complaints,'],
"b":['Non tibi funereos', 'Not from the funerary,'],
"c":['Non tibi bellicrepos', 'Not from the warlike,'],
"d":['Non infelices', 'Not from the unhappy,'],
"e":['Non importunos', 'Not from the troublesome,'],
"f":['Non conclamatos', 'Not from the loud,'],
"g":['Non ærumnosos', 'Not from the wretched,'],
"h":['Non portentosos', 'Not from the ominous,'],
"i":['Non tibi terrificos', 'Not from the terrifying,'],
"k":['Non tibi satidicos', 'Not from the sated,'],
"l":['Non injucundos', 'Not from the unpleasant,'],
"m":['Non tibi mortiferos', 'Not from the deadly,'],
"n":['Non tibi funestos', 'Not from the tragic,'],
"o":['Non tibi damniseros', 'Not from the damaging,'],
"p":['Non tibi damnosos', 'Not from the harmful,'],
"q":['Non tibi ferales', 'Not from the wild,'],
"r":['Non tibi præproperos', 'Not from the hasty,'],
"s":['Non tibi luctisonos', 'Not from the sorrowful,'],
"t":['Non tibi terribiles', 'Not from the terrible,'],
"v":['Non tibi secretos', 'Not from the secret,'],
"w":['Non plorabundos', 'Not from the mourning,'],
"x":['Non infestivos', 'Not from the unfriendly,'],
"z":['Non inpermissos', 'Not from the forbidden,'],
},
{"a":['depinget epistola questus', 'The causes of joy,'],
"b":['depinget epistola casus', 'The letter will depict misfortunes,'],
"c":['evolvet epistola questus', 'The letter will unfold complaints,'],
"d":['evolver epistola casus', 'The letter will unfold misfortunes,'],
"e":['describet epistola questus', 'The letter will describe complaints,'],
"f":['describet epistola casus', 'The letter will describe misfortunes,'],
"g":['narrabit epistola questus', 'The letter will narrate complaints,'],
"h":['narrabit epistola casus', 'The letter will narrate misfortunes,'],
"i":['memorabit epistola questus', 'The letter will mention complaints,'],
"k":['memorabit epistola casus', 'The letter will mention misfortunes,'],
"l":['exponet epistola casus', 'The letter will explain misfortunes,'],
"m":['exponet epistola questus', 'The letter will explain complaints,'],
"n":['effundet epistola questus', 'The letter will pour out complaints,'],
"o":['effundet epistola casus', 'The letter will pour out misfortunes,'],
"p":['mea narrat epistola questus', 'My letter tells of complaints,'],
"q":['mea narrat epistola casus', 'My letter tells of misfortunes,'],
"r":['mea pandet epistola questus', 'My letter reveals complaints,'],
"s":['mea pandet epistola casus', 'My letter reveals misfortunes,'],
"t":['referet mea littera questus', 'My letter reports complaints,'],
"v":['referet mea littera casus', 'My letter reports misfortunes,'],
"w":['pandet mea littera questus', 'The letter will depict misfortunes,'],
"x":['depinget littera casus', 'The letter will describe complaints,'],
"z":['describet littera questus', 'The delights of the mind,'],
},
{"a":['Mentis delicias', 'It lifts and sets free yours,'],
"b":['causas lætitiæ', 'The causes of joy,'],
"c":['lætitiæ causas', 'The delights of sorrow,'],
"d":['luctu delicias', 'The joys of the heart,'],
"e":['Cordis lætitias', 'The delights of the mind,'],
"f":['Delicias animi', 'The delights of sorrow,'],
"g":['Delicias luctu', 'The joys of the mind,'],
"h":['lætitias animi', 'The joys of the mind,'],
"i":['lætitias mentis', 'The delights of the heart,'],
"k":['Cordis delicias', 'Healthy delights,'],
"l":['sanas delicias', 'Holy delights,'],
"m":['sanctas delicias', 'Delights of the soul,'],
"n":['Delicias animæ', 'Delights of the cell,'],
"o":['Cellæ delicias', 'Delights of tears,'],
"p":['Delicias lachrymis', 'Joys of sorrow,'],
"q":['lætitias luctu', 'Delights of peace,'],
"r":['Pacis delicias', 'Holy temptations,'],
"s":['Sanctas illecebras', 'Prefers joys,'],
"t":['Præfica lætitias', 'Sad delights,'],
"v":['tristis delicias', 'Pure temptations,'],
"w":['castas illecebras', 'Temptations for the sad,'],
"x":['Tristibus illecebras', 'Delights of peace,'],
"z":['Delicias pacis', 'It takes care of and preserves yours,'],
},
{"a":['curat & illa tuas', 'The fort is known to you'],
"b":['servat & illa tuas', 'It does not forbid yours,'],
"c":['tollat ut illa tuas', 'It frees and dissolves yours,'],
"d":['non vetat illa tuas', 'It lays low and defeats yours,'],
"e":['solvat ut illa tuas', 'It does not kill yours,'],
"f":['sternat ut illa tuas', 'It loves yours,'],
"g":['non necat illa tuas', 'It takes away and deprives yours,'],
"h":['diligit illa tuas', 'It destroys and loses yours,'],
"i":['demat ut illa tuas', 'I do not take yours,'],
"k":['perdat ut illa tuas', 'I do not disturb yours,'],
"l":['non ego tollo tuas', 'I do not drive yours away,'],
"m":['non ego turbo tuas', 'It drives yours away,'],
"n":['non ego pello tuas', 'It does not snatch yours,'],
"o":['pellat ut illa tuas', 'It perishes yours,'],
"p":['non rapit illa tuas', 'For it nurtures and cherishes yours,'],
"q":['deperit ipsa tuas', 'It breaks and shatters yours,'],
"r":['nam fovet ipsa tuas', 'It tears and bursts yours,'],
"s":['frangat ut illa tuas', 'Break it, that it may be yours'],
"t":['rumpat ut illa tuas', 'Crush it, that it may be yours'],
"v":['pulset ut illa tuas', 'Pulse it, that it may be yours'],
"w":['dejiciendo tuas', 'Let it be yours by falling down'],
"x":['non ego demo, tuas', 'I am not a demon, yours'],
"z":['fors remorando tuas', 'Fate delaying yours'],
},
{"a":['Arx est nota tibi', 'and you do not require our names'],
"b":['grata tibi domus est', 'The house is pleasing to you'],
"c":['sat tibi nota domus', 'The house is familiar to you'],
"d":['est tibi nota domus', 'The house is known to you'],
"e":['est tibi grata domus', 'The house is pleasing to you'],
"f":['est tibi chara domus', 'The house is dear to you'],
"g":['Nota tibi domus est', 'The house is known to you'],
"h":['est bene nota domus', 'The house is well known'],
"i":['chara tibi domus est', 'The house is dear to you'],
"k":['nota est aula tibi', 'The hall is known to you'],
"l":['aula tibi nota est', 'The hall is known to you'],
"m":['ædes chara tibi est', 'The house is dear to you'],
"n":['ædes nota tibi est', 'The house is known to you'],
"o":['cognita sat domus est', 'The house is familiar'],
"p":['est mea nota domus', 'The house is my familiar'],
"q":['est sat nota domus', 'The house is familiar'],
"r":['Patria nota tibi est', 'Your homeland is known to you'],
"s":['Nota tibi patria est', 'Your homeland is known to you'],
"t":['nostra domus nota est', 'Our house is known'],
"v":['Cognita nostra domus', 'Our house is familiar'],
"w":['est dilecta domus', 'The house is beloved'],
"x":['est peramata domus', 'The house is cherished'],
"z":['Non domus exosa est', 'The house is not despised'],
},
{"a":['nec nomina nostra requires', 'You are a part of my heart'],
"b":['quæ talia vidit arantem', 'that saw such things when plowing'],
"c":['quæ carmina vidit arantem', 'that saw such songs when plowing'],
"d":['notus tibi carminis author', 'the author of the song known to you'],
"e":['qua Vates Incola vivit', 'where the Poet lives as an Inhabitant'],
"f":['qua Vates prodiit olim', 'where the Poet once emerged'],
"g":['quæ nostro carmine gaudet', 'who rejoices in our song'],
"h":['quæ te veneratur, & audit', 'who reveres and hears you'],
"i":['notus, quem diligis, author', 'the known author whom you love'],
"k":['quæ pro te metra paravit', 'who prepared verses for you'],
"l":['notus, qui scribit, amicus', 'the known author, who writes, is a friend'],
"m":['qui scripsit, notus amicus', 'who wrote, known friend'],
"n":['charus, qui carmine ludit,', 'dear one who plays with song,'],
"o":['gratus, qui metra paravit', 'grateful one who prepared verses'],
"p":['multo fum cognitus ufu,', 'much used by smoke,'],
"q":['multos tibi culta per annos', 'cultivated by you for many years'],
"r":['chari, gratique fodalis,', 'dear, loyal farmhands,'],
"s":['qua degit carminis author', 'where the author of the song resides'],
"t":['qua præsens littera prodit', 'where the present letter emerges'],
"v":['qua dulcis epistola venit', 'where the sweet letter comes'],
"w":['chari, gratique penates', 'dear, beloved home'],
"x":['scribentis stemma, manusque', 'the genealogy and hand of the writer'],
"z":['scriptoris dextra, genusque', 'the right hand and family of the writer'],
},
{"a":['Tu mihi pars cordis', 'and my delights'],
"b":['tu mihi præsidium', 'you are my protection'],
"c":['semper eras Tutor', 'you were always my tutor'],
"d":['semper eras Ductor,', 'you were always my guide,'],
"e":['semper eras Pylades', 'you were always my Pylades'],
"f":['Tu mihi cordis amor', 'You are the love of my heart'],
"g":['tu mihi cor cordis', 'you are my heart\'s heart'],
"h":['Tu mihi dulcis amor', 'You are the sweet love of my heart'],
"i":['semper Nisus eras', 'you were always my Nisus'],
"k":['Tu mihi Patronus', 'You are my patron'],
"l":['Tu mihi Mecenas', 'You are my patron'],
"m":['Tu mihi Protector', 'You are my protector'],
"n":['Tu tutela mihi', 'You are my protection'],
"o":['Tu grandis Fautor', 'You were a great supporter'],
"p":['Tu Benefactor eras', 'You were a benefactor'],
"q":['Auxilio fueras', 'You were a help'],
"r":['Præsidium fueras', 'You were a protection'],
"s":['Patronus mihi tu', 'You are my patron'],
"t":['Tu mihi solamen', 'You are my solace'],
"v":['Mecænas fueras', 'You were my patron'],
"w":['Ductor semper eras', 'You were always my guide'],
"x":['Te colo fautorem,', 'I honor you as a supporter,'],
"z":['Te colo Patronum', 'I honor you as a patron'],
},
{"a":['Deliciæque mex', 'You follow justice'],
"b":['Gloria quanta mihi!', 'What glory for me!'],
"c":['Numinis ecce favor', 'Behold the favor of a god'],
"d":['Dux meus, alter ego', 'My leader, my alter ego'],
"e":['Theseus, alter ego', 'Theseus, my alter ego'],
"f":['Duxque, salusque meis', 'My leader and my salvation'],
"g":['Duxque, salusque mihi', 'My leader and my salvation for me'],
"h":['Spes mea, dulce decus', 'My hope, sweet splendor'],
"i":['Lux mea, dulce decus', 'My light, sweet splendor'],
"k":['Lux mea, dextra mihi', 'My light, my right hand'],
"l":['gratia summa mihi', 'greatest grace for me'],
"m":['perge manere, precor', 'I beg you, please stay'],
"n":['quod mihi nemo neget', 'What no one denies me'],
"o":['quis neget ista mihi?', 'Who would deny me these things?'],
"p":['magne repende Deus!', 'Great God, repay!'],
"q":['quod benefacta notant', 'What good deeds show'],
"r":['debeo cuncta tibi', 'I owe everything to you'],
"s":['quod mea Musa canit', 'What my muse sings'],
"t":['quod mea Musa canet', 'What my muse will sing'],
"v":['tempus in omne mane', 'Forever in all morning'],
"w":['non ego dignus eram', 'I was not worthy'],
"x":['talis & usque mane', 'Such and forever morning'],
"z":['perge favere precor', 'I beg you to continue to favor me'],
},
{"a":['Justitiam sequeris', 'You shine with great integrity'],
"b":['Virtutem sequeris', 'You follow virtue'],
"c":['sectaris Themidem', 'You pursue Themis'],
"d":['Tu recti custos', 'You are the guardian of righteousness'],
"e":['Justitiam observas', 'You observe justice'],
"f":['Tu candoris amans', 'You are a lover of integrity'],
"g":['Justitiam servas', 'You uphold justice'],
"h":['Non nisi justa facis', 'You do nothing but what is just'],
"i":['Cuique suum tribuis', 'You give to each what is theirs'],
"k":['Jura tueris amans', 'You love to uphold the laws'],
"l":['Grandia facta geris', 'You accomplish great deeds'],
"m":['Consilio gravis es', 'You are a weighty counselor'],
"n":['Majestate vales', 'You are strong in majesty'],
"o":['Consilio polles', 'You excel in counsel'],
"p":['Polles consilio', 'You excel in counsel'],
"q":['Eloquio prestas', 'You excel in eloquence'],
"r":['Judicio polles', 'You excel in judgment'],
"s":['Judicio prestas', 'You excel in judgment'],
"t":['Polles ingenio', 'You excel in intellect'],
"v":['Ingenio prestas', 'You excel in intellect'],
"w":['Laudari refugis', 'You avoid praise'],
"x":['Non tibi laudis amor', 'You do not love praise'],
"z":['laudari renuis.', 'You refuse to be praised.'],
},
{"a":['magna probitate coruscas', 'no harm weighs you down'],
"b":['multa pietate coruscas', 'You shine with much piety'],
"c":['famæ mendacia rides', 'You laugh at the falsehoods of fame'],
"d":['legum nec amantior alter', 'no one is more fond of laws'],
"e":['pietatis idoneus author', 'a suitable author of piety'],
"f":['nulli pietate secundus', 'second to none in piety'],
"g":['pietatem pectore spiras', 'you breathe piety from your heart'],
"h":['solidæ pietatis alumnus', 'a student of solid piety'],
"i":['tibi Christi nomen amori', 'for you the name of Christ is a love'],
"k":['pietas tibi plurima cordi', 'piety is of great importance to you'],
"l":['pietas te laudibus ornat', 'piety adorns you with praise'],
"m":['sanctæ pietatis imago es', 'you are the image of holy piety'],
"n":['probitatis laude coruscas', 'you shine with the praise of integrity'],
"o":['pietas te nutrit alumnum', 'piety nurtures you as a student'],
"p":['servas mandata Tonantis', 'you keep the commands of the thunderer'],
"q":['totusque â Numine pendes', 'and you depend entirely on the deity'],
"r":['tibi mens sapit integra colum', 'your mind is wise and upright'],
"s":['pietas tibi maxima rerum', 'piety is the greatest thing for you'],
"t":['pietas tibi pectore fixa est', 'piety is fixed in your heart'],
"v":['vera pietate coruscas', 'you shine with true piety'],
"w":['concludis pectore cœlum', 'you close heaven in your heart'],
"x":['probitas te gaudet alumno', 'integrity rejoices in you as a student'],
"z":['pietas te gaudet Achate', 'piety rejoices in you as a companion'],
},
{"a":['Haud te noxa premit', 'your only hope is God'],
"b":['Indolis es placidæ', 'you are of a peaceful nature'],
"c":['Non vitiis traheris', 'you are not led by vices'],
"d":['Criminis innocuus', 'guiltless of crime'],
"e":['Numine digna sapis', 'you are wise worthy of the deity'],
"f":['Exemplar morum es', 'you are an example of morals'],
"g":['Grande decus patriæ es', 'you are a great honor for your country'],
"h":['Integer es vitæ', 'you are pure in your life'],
"i":['Es purus sceleris', 'you are free from wickedness'],
"k":['Expers tu sceleris', 'you are unacquainted with wickedness'],
"l":['Cedro digna geris', 'you bear things worthy of cedar'],
"m":['Marmore digna geris', 'you bear things worthy of marble'],
"n":['Cunctis diligeris', 'you are loved by all'],
"o":['Te genus exornat', 'your family adorns you'],
"p":['Diligeris cunctis', 'you are loved by all'],
"q":['Devincis cunctos', 'you surpass all'],
"r":['Magnus in adversis', 'great in adversity'],
"s":['Castior Hippolito es', 'more chaste than Hippolytus'],
"t":['Quantum animo prestas!', 'how much you excel in spirit!'],
"v":['Fortior adversis', 'stronger in adversity'],
"w":['Quis te digna canet?', 'who would sing of you worthily?'],
"x":['Vis generosa tibi', 'you have a generous spirit'],
"z":['Excellis cunctos', 'you excel all'],
},
{"a":['Spes tua sola Deus','god is your only hope'],
"b":['Candida corda geris', 'you bear pure hearts'],
"c":['Lactea corda geris', 'you bear milk-white hearts'],
"d":['Corda pudica geris', 'you bear modest hearts'],
"e":['Cor patientis habes', 'you have a patient heart'],
"f":['Non tibi nota Venus', 'love is not known to you'],
"g":['Quot tibi mentis opes!', 'how many resources of mind you have!'],
"h":['pectore fucus abest', 'deceit is absent from your heart'],
"i":['sidera mente geris', 'you bear the stars in your mind'],
"k":['fors bona semper amet!', 'May good fortune always love you!'],
"l":['semper ad alta volas', 'You always aim for higher things'],
"m":['celsius ire nequis', 'No one can go higher'],
"n":['nomen ad astra vehis', 'You take your name to the stars'],
"o":['mens tibi casta placet', 'A chaste mind is pleasing to you'],
"p":['mens tibi pura placer', 'A pure mind is pleasing to you'],
"q":['fama perennis erit', 'Your fame will be eternal'],
"r":['non tibi parca manus', 'The hand of the gods is not stingy with you'],
"s":['quam tibi larga manus', 'What bountiful gifts the gods give to you'],
"t":['non tibi fastus inest', 'Pride does not dwell in you'],
"v":['te Cytherea fugit', 'Aphrodite avoids you'],
"w":['spes tua tota Deus', 'Your only hope is God'],
"x":['mens animosa tibi', 'You have a brave mind'],
"z":['Dona quot alma tibi!', 'How many dear gifts the gods give to you!'],
}]