table = [{'a':'Ne mora te teneat,',
'b':'Ne cunctare precor,',
'c':'Diva Thalia jubet,',
'd':'Docta Thalia jubet,',
'e':'Eja agedum! Lubeat,',
'f':'Quod peto, sponte voles,',
'g':'Quod precor, ipse voles,',
'h':'Ne dedigneris,',
'i':'Sit tibi chare placens,',
'k':'Non detrectabis,',
'l':'Promptus, Amice, velis,',
'm':'Te mora nulla liget,',
'n':'Haud erit ingratum,',
'o':'Ne grave fit, quæso,',
'p':'Dignare, obtestor,',
'q':'Haud, credo renues,',
'r':'Non tibi displiceat,',
's':'Ne tibi displiceat,',
't':'Præses Apollo jubet,',
'v':'Pieris alma jubet,',
'w':'Te mandat Phoebus,',
'x':'Sponte tua cupies,',
'z':'Spero, non renues,',
},
{'a':'chartæ perfringere gemmam,',
'b':'fua vincula demere chartæ,',
'c':'tectis admittere chartam,',
'd':'præsentem evolvere chartam,',
'e':'peregrinam evolvere chartam,',
'f':'concedere lumina chartæ,',
'g':'percurrere lumine chartam,',
'h':'nostram acceptare tabellam,',
'i':'chartæ perfringere ceram,',
'k':'chartam lustrare legendo,',
'l':'lustare hanc lumine chartam,',
'm':'lustare legendo tabellam,',
'n':'fua vincula tollere chartæ,',
'o':'vúltum concedere chartæ,',
'p':'valtum indulgere tabellæ,',
'q':'fua vincula solvere chartae,',
'r':'quam cernis volvere chartam,',
's':'fua vincula rumpere chartae,',
't':'peregrinam volvere chartam,',
'v':'nostræ dare lumina chartæ,',
'w':'fua tollere vincula tabellæ,',
'x':'concedere limina chartæ,',
'z':'præsentem volvere chartam,',
},
{'a':'Non ex ignotis,',
'b':'Non ex ingratis,',
'c':'Non ex Odrysiis,',
'd':'Non ex barbaricis,',
'e':'Non ex Sarmaticis,',
'f':'E tibi jucundis,',
'g':'Ex tibi jucundis,',
'h':'E tibi dilectis,',
'i':'Ex tibi dilectis,',
'k':': E tibi ter charts,',
'l':'Ex tibi pergratis;',
'm':'Ex tibi fat notis,',
'n':'Non ex infaustis,',
'o':'Non ex invisis,',
'p':'Non ex Iliacis,',
'q':'Non ex fædifragis,',
'r':'a tibi dilectis,',
's':'a tibi pergratis,',
't':'à tibi fat notis,',
'v':'E fortunatis,',
'w':'Neutiquam ab ignotis,',
'x':'Ex non ignotis,',
'z':'Ex non ingratis,',
},
{'a':'Scribitur illa plagis',
'b':'mittitur illa plagis',
'c':'advenit illa plagis',
'd':'devenit illa plagis',
'e':'prodiit illa plagis',
'f':'hanc tibi mitto plagis',
'g':'& ea misa plagis',
'h':'& ea scripta plagis',
'i':'crede, venire plagis',
'k':'dat tibi penna plagis,',
'l':'tractibus illa venit',
'm':'partibus illa venit',
'n':'sedibus illa venit',
'o':'sinibus illa venit',
'p':'scribitur illa locis',
'q':'mittitur illa locis',
'r':'advenit illa locis',
's':'devenit illa locis',
't':'prodiit illa locis',
'v':'hanc tibi mitto locis',
'w':'est ea missa locis',
'x':'est ea scripta locis',
'z':'hanc tibi scribo Locis',
},
{'a':'Non tibi satales',
'b':'Non tibi funereos',
'c':'Non tibi bellicrepos',
'd':'Non infelices',
'e':'Non importunos',
'f':'Non conclamatos',
'g':'Non ærumnosos',
'h':'Non portentosos',
'i':'Non tibi terrificos',
'k':'Non tibi satidicos',
'l':'Non injucundos',
'm':'Non tibi mortiferos',
'n':'Non tibi funestos',
'o':'Non tibi damniseros',
'p':'Non tibi damnosos',
'q':'Non tibi ferales',
'r':'Non tibi præproperos',
's':'Non tibi luctisonos',
't':'Non tibi terribiles',
'v':'Non tibi secretos',
'w':'Non plorabundos',
'x':'Non infestivos',
'z':'Non inpermissos',
},
{'a':'depinget epistola questus',
'b':'depinget epistola casus',
'c':'evolvet epistola questus',
'd':'evolver epistola casus',
'e':'describet epistola questus',
'f':'describet epistola casus',
'g':'narrabit epistola questus',
'h':'narrabit epistola casus',
'i':'memorabit epistola questus',
'k':'memorabit epistola casus',
'l':'exponet epistola casus',
'm':'exponet epistola questus',
'n':'effundet epistola questus',
'o':'effundet epistola casus',
'p':'mea narrat epistola questus',
'q':'mea narrat epistola casus',
'r':'mea pandet epistola questus',
's':'mea pandet epistola casus',
't':'referet mea littera questus',
'v':'referet mea littera casus',
'w':'pandet mea littera questus',
'x':'depinget littera casus',
'z':'describet littera questus',
},
{'a':'Mentis delicias',
'b':'causas lætitiæ',
'c':'lætitiæ causas',
'd':'luctu delicias',
'e':'Cordis lætitias',
'f':'Delicias animi',
'g':'Delicias luctu',
'h':'lætitias animi',
'i':'lætitias mentis',
'k':'Cordis delicias',
'l':'sanas delicias',
'm':'sanctas delicias',
'n':'Delicias animæ',
'o':'Cellæ delicias',
'p':'Delicias lachrymis',
'q':'lætitias luctu',
'r':'Pacis delicias',
's':'Sanctas illecebras',
't':'Præfica lætitias',
'v':'tristis delicias',
'w':'castas illecebras',
'x':'Tristibus illecebras',
'z':'Delicias pacis',
},
{'a':'curat & illa tuas',
'b':'servat & illa tuas',
'c':'tollat ut illa tuas',
'd':'non vetat illa tuas',
'e':'solvat ut illa tuas',
'f':'sternat ut illa tuas',
'g':'non necat illa tuas',
'h':'diligit illa tuas',
'i':'demat ut illa tuas',
'k':'perdat ut illa tuas',
'l':'non ego tollo tuas',
'm':'non ego turbo tuas',
'n':'non ego pello tuas',
'o':'pellat ut illa tuas',
'p':'non rapit illa tuas',
'q':'deperit ipsa tuas',
'r':'nam fovet ipsa tuas',
's':'frangat ut illa tuas',
't':'rumpat ut illa tuas',
'v':'pulset ut illa tuas',
'w':'dejiciendo tuas',
'x':'non ego demo, tuas',
'z':'fors remorando tuas',
},
{'a':'Arx est nota tibi',
'b':'grata tibi domus est',
'c':'sat tibi nota domus',
'd':'est tibi nota domus',
'e':'est tibi grata domus',
'f':'est tibi chara domus',
'g':'Nota tibi domus est',
'h':'est bene nota domus',
'i':'chara tibi domus est',
'k':'nota est aula tibi',
'l':'aula tibi nota est',
'm':'ædes chara tibi est',
'n':'ædes nota tibi est',
'o':'cognita sat domus est',
'p':'est mea nota domus',
'q':'est sat nota domus',
'r':'Patria nota tibi est',
's':'Nota tibi patria est',
't':'nostra domus nota est',
'v':'Cognita nostra domus',
'w':'est dilecta domus',
'x':'est peramata domus',
'z':'Non domus exosa est',
},
{'a':'nec nomina nostra requires',
'b':'quæ talia vidit arantem',
'c':'quæ carmina vidit arantem',
'd':'notus tibi carminis author',
'e':'qua Vates Incola vivit',
'f':'qua Vates prodiit olim',
'g':'quæ nostro carmine gaudet',
'h':'quæ te veneratur, & audit',
'i':'notus, quem diligis, author',
'k':'quæ pro te metra paravit',
'l':'notus, qui scribit, amicus',
'm':'qui scripsit, notus amicus',
'n':'charus, qui carmine ludit,',
'o':'gratus, qui metra paravit',
'p':'multo fum cognitus ufu,',
'q':'multos tibi culta per annos',
'r':'chari, gratique fodalis,',
's':'qua degit carminis author',
't':'qua præsens littera prodit',
'v':'qua dulcis epistola venit',
'w':'chari, gratique penates',
'x':'scribentis stemma, manusque',
'z':'scriptoris dextra, genusque',
},
{'a':'Tu mihi pars cordis',
'b':'tu mihi præsidium',
'c':'semper eras Tutor',
'd':'semper eras Ductor,',
'e':'semper eras Pylades',
'f':'Tu mihi cordis amor',
'g':'tu mihi cor cordis',
'h':'Tu mihi dulcis amor',
'i':'semper Nisus eras',
'k':'Tu mihi Patronus',
'l':'Tu mihi Mecenas',
'm':'Tu mihi Protector',
'n':'Tu tutela mihi',
'o':'Tu grandis Fautor',
'p':'Tu Benefactor eras',
'q':'Auxilio fueras',
'r':'Præsidium fueras',
's':'Patronus mihi tu',
't':'Tu mihi solamen',
'v':'Mecænas fueras',
'w':'Ductor semper eras',
'x':'Te colo fautorem,',
'z':'Te colo Patronum',
},
{'a':'Deliciæque mex',
'b':'Gloria quanta mihi!',
'c':'Numinis ecce favor',
'd':'Dux meus, alter ego',
'e':'Theseus, alter ego',
'f':'Duxque, salusque meis',
'g':'Duxque, salusque mihi',
'h':'Spes mea, dulce decus',
'i':'Lux mea, dulce decus',
'k':'Lux mea, dextra mihi',
'l':'gratia summa mihi',
'm':'perge manere, precor',
'n':'quod mihi nemo neget',
'o':'quis neget ista mihi?',
'p':'magne repende Deus!',
'q':'quod benefacta notant',
'r':'debeo cuncta tibi',
's':'quod mea Musa canit',
't':'quod mea Musa canet',
'v':'tempus in omne mane',
'w':'non ego dignus eram',
'x':'talis & usque mane',
'z':'perge favere precor',
},
{'a':'Justitiam sequeris',
'b':'Virtutem sequeris',
'c':'sectaris Themidem',
'd':'Tu recti custos',
'e':'Justitiam observas',
'f':'Tu candoris amans',
'g':'Justitiam servas',
'h':'Non nisi justa facis',
'i':'Cuique suum tribuis',
'k':'Jura tueris amans',
'l':'Grandia facta geris',
'm':'Consilio gravis es',
'n':'Majestate vales',
'o':'Consilio polles',
'p':'Polles consilio',
'q':'Eloquio prestas',
'r':'Judicio polles',
's':'Judicio prestas',
't':'Polles ingenio',
'v':'Ingenio prestas',
'w':'Laudari refugis',
'x':'Non tibi laudis amor',
'z':'laudari renuis.',
},
{'a':'magna probitate coruscas',
'b':'multa pietate coruscas',
'c':'famæ mendacia rides',
'd':'legum nec amantior alter',
'e':'pietatis idoneus author',
'f':'nulli pietate secundus',
'g':'pietatem pectore spiras',
'h':'solidæ pietatis alumnus',
'i':'tibi Christi nomen amori',
'k':'pietas tibi plurima cordi',
'l':'pietas te laudibus ornat',
'm':'sanctæ pietatis imago es',
'n':'probitatis laude coruscas',
'o':'pietas te nutrit alumnum',
'p':'servas mandata Tonantis',
'q':'totusque â Numine pendes',
'r':'tibi mens sapit integra colum',
's':'pietas tibi maxima rerum',
't':'pietas tibi pectore fixa est',
'v':'vera pietate coruscas',
'w':'concludis pectore cœlum',
'x':'probitas te gaudet alumno',
'z':'pietas te gaudet Achate',
},
{'a':'Haud te noxa premit',
'b':'Indolis es placidæ',
'c':'Non vitiis traheris',
'd':'Criminis innocuus',
'e':'Numine digna sapis',
'f':'Exemplar morum es',
'g':'Grande decus patriæ es',
'h':'Integer es vitæ',
'i':'Es purus sceleris',
'k':'Expers tu sceleris',
'l':'Cedro digna geris',
'm':'Marmore digna geris',
'n':'Cunctis diligeris',
'o':'Te genus exornat',
'p':'Diligeris cunctis',
'q':'Devincis cunctos',
'r':'Magnus in adversis',
's':'Castior Hippolito es',
't':'Quantum animo prestas!',
'v':'Fortior adversis',
'w':'Quis te digna canet?',
'x':'Vis generosa tibi',
'z':'Excellis cunctos',
},
{'a':'Spes tua sola Deus',
'b':'Candida corda geris',
'c':'Lactea corda geris',
'd':'Corda pudica geris',
'e':'Cor patientis habes',
'f':'Non tibi nota Venus',
'g':'Quot tibi mentis opes!',
'h':'pectore fucus abest',
'i':'sidera mente geris',
'k':'fors bona semper amet!',
'l':'semper ad alta volas',
'm':'celsius ire nequis',
'n':'nomen ad astra vehis',
'o':'mens tibi casta placet',
'p':'mens tibi pura placer',
'q':'fama perennis erit',
'r':'non tibi parca manus',
's':'quam tibi larga manus',
't':'non tibi fastus inest',
'v':'te Cytherea fugit',
'w':'spes tua tota Deus',
'x':'mens animosa tibi',
'z':'Dona quot alma tibi!',
}]