table = [{'a':'Ne mora te teneat,',
'b':'Ne cunctare precor,',
'c':'Diva Thalia jubet,',
'd':'Docta Thalia jubet,',
'e':'Eja agedum! Lubeat,',
'f':'Quod peto, sponte voles,',
'g':'Quod precor, ipfe voles,',
'h':'Ne dedigneris,',
'i':'Sit tibi chare placens,',
'k':'Non detrectabis,',
'l':'Promptus, Amice, velis,',
'm':'Te mora nulla liget,',
'n':'Haud erit ingratum,',
'o':'Ne grave fit, quæfo,',
'p':'Dignare, obteftor,',
'q':'Haud, credo renues,',
'r':'Non tibi difpliceat,',
's':'Ne tibi difpliceat,',
't':'Præfes Apollo jubet,',
'v':'Pieris alma jubet,',
'w':'Te mandat Phoebus,',
'x':'Sponte tua cupies,',
'z':'Spero, non renues,',
},
{'a':'chartæ perfringere gemmam,',
'b':'fua vincula demere chartæ,',
'c':'tectis admittere chartam,',
'd':'præfentem evolvere chartam,',
'e':'peregrinam evolvere chartam,',
'f':'concedere lumina chartæ,',
'g':'percurrere lumine chartam,',
'h':'noftram acceptare tabellam,',
'i':'chartæ perfringere ceram,',
'k':'chartam luftrare legendo,',
'l':'luftrare hanc lumine chartam,',
'm':'luftrare legendo tabellam,',
'n':'fua vincula tollere chartæ,',
'o':'vúltum concedere chartæ,',
'p':'valtum indulgere tabellæ,',
'q':'fua vincula folvere chartae,',
'r':'quam cernis volvere chartam,',
's':'fua vincula rumpere chartae,',
't':'peregrinam volvere chartam,',
'v':'noftræ dare lumina chartæ,',
'w':'fua tollere vincula tabellæ,',
'x':'concedere limina chartæ,',
'z':'præfentem volvere chartam,',
},
{'a':'Non ex ignotis,',
'b':'Non ex ingratis,',
'c':'Non ex Odryfiis,',
'd':'Non ex barbaricis,',
'e':'Non ex Sarmaticis,',
'f':'E tibi jucundis,',
'g':'Ex tibi jucundis,',
'h':'E tibi dilectis,',
'i':'Ex tibi dilectis,',
'k':': E tibi ter charts,',
'l':'Ex tibi pergratis;',
'm':'Ex tibi fat notis,',
'n':'Non ex infauftis,',
'o':'Non ex invifis,',
'p':'Non ex Iliacis,',
'q':'Non ex fædifragis,',
'r':'a tibi dilectis,',
's':'a tibi pergratis,',
't':'à tibi fat notis,',
'v':'E fortunatis,',
'w':'Neutiquam ab ignotis,',
'x':'Ex non ignotis,',
'z':'Ex non ingratis,',
},
{'a':'Scribitur illa plagis',
'b':'mittitur illa plagis',
'c':'advenit illa plagis',
'd':'devenit illa plagis.',
'e':'prodiit illa plagis',
'f':'hanc tibi mitto plagis',
'g':'& ea miffa plagis',
'h':'& ea fcripta plagis ',
'i': 'crede, venire plagis',
'k':'dat tibi penna plagis,',
'l':'tractibus illa venit',
'm':'partibus illa venit',
'n':'fedibus illa venit',
'o':'finibus illa venit',
'p':'scribitur illa locis',
'q':'mittitur illa locis',
'r':'advenit illa locis',
's':'devenit illa locis',
't':'prodiit illa locis',
'v':'hanc tibi mitto locis',
'w':'est ea miffa locis.',
'x':'est ea scripta locis',
'z':'hanc tibi scribo Locis',
}]